# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvehicle.proto\x12\x08vehicles\"V\n\x07Vehicle\x12\x11\n\tmatricula\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x0e\n\x06modelo\x18\x03 \x01(\t\x12\r\n\x05marca\x18\x04 \x01(\t\x12\x0c\n\x04tipo\x18\x05 \x01(\t\"\x1e\n\tVehicleId\x12\x11\n\tmatricula\x18\x01 \x01(\t\"2\n\x0bVehicleList\x12#\n\x08vehicles\x18\x01 \x03(\x0b\x32\x11.vehicles.Vehicle\"\x07\n\x05\x45mpty\".\n\x0fOperationStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfe\x01\n\x0eVehicleService\x12=\n\rCreateVehicle\x12\x11.vehicles.Vehicle\x1a\x19.vehicles.OperationStatus\x12\x34\n\nGetVehicle\x12\x13.vehicles.VehicleId\x1a\x11.vehicles.Vehicle\x12\x36\n\x0cListVehicles\x12\x0f.vehicles.Empty\x1a\x15.vehicles.VehicleList\x12?\n\rDeleteVehicle\x12\x13.vehicles.VehicleId\x1a\x19.vehicles.OperationStatusB&\n\x14\x63om.example.vehiclesB\x0cVehicleProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.example.vehiclesB\014VehicleProtoP\001'
  _globals['_VEHICLE']._serialized_start=27
  _globals['_VEHICLE']._serialized_end=113
  _globals['_VEHICLEID']._serialized_start=115
  _globals['_VEHICLEID']._serialized_end=145
  _globals['_VEHICLELIST']._serialized_start=147
  _globals['_VEHICLELIST']._serialized_end=197
  _globals['_EMPTY']._serialized_start=199
  _globals['_EMPTY']._serialized_end=206
  _globals['_OPERATIONSTATUS']._serialized_start=208
  _globals['_OPERATIONSTATUS']._serialized_end=254
  _globals['_VEHICLESERVICE']._serialized_start=257
  _globals['_VEHICLESERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
