# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vehicle_pb2 as vehicle__pb2


class VehicleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVehicle = channel.unary_unary(
                '/vehicles.VehicleService/CreateVehicle',
                request_serializer=vehicle__pb2.Vehicle.SerializeToString,
                response_deserializer=vehicle__pb2.OperationStatus.FromString,
                )
        self.GetVehicle = channel.unary_unary(
                '/vehicles.VehicleService/GetVehicle',
                request_serializer=vehicle__pb2.VehicleId.SerializeToString,
                response_deserializer=vehicle__pb2.Vehicle.FromString,
                )
        self.ListVehicles = channel.unary_unary(
                '/vehicles.VehicleService/ListVehicles',
                request_serializer=vehicle__pb2.Empty.SerializeToString,
                response_deserializer=vehicle__pb2.VehicleList.FromString,
                )
        self.DeleteVehicle = channel.unary_unary(
                '/vehicles.VehicleService/DeleteVehicle',
                request_serializer=vehicle__pb2.VehicleId.SerializeToString,
                response_deserializer=vehicle__pb2.OperationStatus.FromString,
                )


class VehicleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVehicles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVehicle,
                    request_deserializer=vehicle__pb2.Vehicle.FromString,
                    response_serializer=vehicle__pb2.OperationStatus.SerializeToString,
            ),
            'GetVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicle,
                    request_deserializer=vehicle__pb2.VehicleId.FromString,
                    response_serializer=vehicle__pb2.Vehicle.SerializeToString,
            ),
            'ListVehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVehicles,
                    request_deserializer=vehicle__pb2.Empty.FromString,
                    response_serializer=vehicle__pb2.VehicleList.SerializeToString,
            ),
            'DeleteVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVehicle,
                    request_deserializer=vehicle__pb2.VehicleId.FromString,
                    response_serializer=vehicle__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicles.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VehicleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicles.VehicleService/CreateVehicle',
            vehicle__pb2.Vehicle.SerializeToString,
            vehicle__pb2.OperationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicles.VehicleService/GetVehicle',
            vehicle__pb2.VehicleId.SerializeToString,
            vehicle__pb2.Vehicle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicles.VehicleService/ListVehicles',
            vehicle__pb2.Empty.SerializeToString,
            vehicle__pb2.VehicleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vehicles.VehicleService/DeleteVehicle',
            vehicle__pb2.VehicleId.SerializeToString,
            vehicle__pb2.OperationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
